var backend_script=mosConfig_live_site+'/modules/mod_ezine_newsletter.ajax.php';var ezine_newsletter_ajax_engine='';function initNsAjaxEngine(){if(ezine_newsletter_ajax_engine==''){ezine_newsletter_ajax_engine=new d4j_ajax_engine();ezine_newsletter_ajax_engine.setResponseUpdate('function');}}
function validateEmail(eml){var filter=/^([\w-]+(?:\.[\w-]+)*)@((?:[\w-]+\.)*\w[\w-]{0,66})\.([a-z]{2,6}(?:\.[a-z]{2})?)$/i
if(filter.test(eml)){return true;}else{alert(_VALID_EMAIL_REQUIRED);return false;}}
function call_subscribe(){initNsAjaxEngine();var this_form=document.mod_ezine_newsletter;if(typeof this_form.uid!='undefined'||validateEmail(this_form.email.value)){var selected_pages='';for(var i=0;i<this_form.checkbox.value;i++){var cb=eval('this_form.cb'+i+'');if(cb.checked==true){selected_pages+=cb.value+',';}}
selected_pages=selected_pages.substring(0,selected_pages.length-1);if(selected_pages==''){alert(_SELECT_PAGE_TO_SUBSCRIBE_TO);return false;}
if(typeof this_form.uid!='undefined'){var query='uid='+this_form.uid.value;}else if(typeof this_form.email!='undefined'&&this_form.email.value!=''){var query='email='+this_form.email.value;}else{alert(_FORGOT_INPUT_EMAIL_ADDRESS);return false;}
this_form.submit_button.setAttribute('title',this_form.submit_button.value);this_form.submit_button.value='Processing...';ezine_newsletter_ajax_engine.sendRequest(backend_script,response_subscribe,'func=subscribe','pages='+selected_pages,query,'name='+this_form.name.value);}}
function response_subscribe(result){var this_form=document.mod_ezine_newsletter;if(result.getElementsByTagName('ajaxResponse').item(0).getAttribute('success')=='true'){var subscribed_pages=result.getElementsByTagName('ajaxResponse').item(0).firstChild.data.split(',');for(var i=0;i<this_form.checkbox.value;i++){var cb=eval('this_form.cb'+i+'');var found=false;for(var j=0;j<subscribed_pages.length;j++){if(cb.value==subscribed_pages[j]){cb.checked=true;found=true;}
if(found==false){cb.checked=false;}}}
alert(_SUBSCRIBE_SUCCESS);}else{alert(_SUBSCRIBE_FAIL);}
this_form.submit_button.value=this_form.submit_button.getAttribute('title');this_form.submit_button.removeAttribute('title');}
function call_unsubscribe(){initNsAjaxEngine();var this_form=document.mod_ezine_newsletter;if(typeof this_form.uid!='undefined'||validateEmail(this_form.email.value)){var selected_pages='';for(var i=0;i<this_form.checkbox.value;i++){var cb=eval('this_form.cb'+i+'');if(cb.checked==true){selected_pages+=cb.value+',';}}
selected_pages=selected_pages.substring(0,selected_pages.length-1);if(selected_pages==''){alert(_SELECT_PAGE_TO_UNSUBSCRIBE_FROM);return false;}
if(typeof this_form.uid!='undefined'){var query='uid='+this_form.uid.value;}else if(typeof this_form.email!='undefined'&&this_form.email.value!=''){var query='email='+this_form.email.value;}else{alert(_FORGOT_INPUT_EMAIL_ADDRESS);return false;}
this_form.submit_button.setAttribute('title',this_form.submit_button.value);this_form.submit_button.value='Processing...';ezine_newsletter_ajax_engine.sendRequest(backend_script,response_unsubscribe,'func=unsubscribe','pages='+selected_pages,query);}}
function response_unsubscribe(result){var this_form=document.mod_ezine_newsletter;if(result.getElementsByTagName('ajaxResponse').item(0).getAttribute('success')=='true'){if(typeof this_form.dontListPage=='undefined'){var subscribed_pages=result.getElementsByTagName('ajaxResponse').item(0).firstChild.data.split(',');for(var i=0;i<this_form.checkbox.value;i++){var cb=eval('this_form.cb'+i+'');var found=false;for(var j=0;j<subscribed_pages.length;j++){if(cb.value==subscribed_pages[j]){cb.checked=true;found=true;}
if(found==false){cb.checked=false;}}}}
alert(_UNSUBSCRIBE_SUCCESS);}else{alert(_UNSUBSCRIBE_FAIL);}
this_form.submit_button.value=this_form.submit_button.getAttribute('title');this_form.submit_button.removeAttribute('title');}